Document: smartvirdebug
Title: Debian smartvirdebug Manual
Author: <insert document author here>
Abstract: This manual describes what smartvirdebug is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smartvirdebug/smartvirdebug.sgml.gz

Format: postscript
Files: /usr/share/doc/smartvirdebug/smartvirdebug.ps.gz

Format: text
Files: /usr/share/doc/smartvirdebug/smartvirdebug.text.gz

Format: HTML
Index: /usr/share/doc/smartvirdebug/html/index.html
Files: /usr/share/doc/smartvirdebug/html/*.html
